---
- name: Install Nginx
  host: all
  tasks:
    - name: install nginx on debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: install nginx on redhat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "Red Hat"